services:
  server:
    build: ./
    container_name: server
    ports:
      - 3000:3000
    volumes:
      - logs:/app/logs
      - .:/app
      - /app/node_modules
    depends_on:
      - directus

  directus:
    image: directus/directus:latest
    container_name: directus
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
    env_file:
      - ./env/directus.env
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:16.2-alpine
    restart: always
    container_name: database
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - ./env/postgres.env
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
  logs:
